'use client'

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion'

const refs = [
  {
    id: 'automata-types',
    title: 'Automata Hierarchy',
    items: [
      { label: 'DFA', desc: 'Deterministic Finite Automaton — exactly one transition per (state, symbol)' },
      { label: 'NFA', desc: 'Nondeterministic FA — multiple transitions allowed; equivalent to DFA' },
      { label: 'PDA', desc: 'Pushdown Automaton — NFA + stack; recognizes CFLs' },
      { label: 'LBA', desc: 'Linear Bounded Automaton — TM bounded by input length' },
      { label: 'TM', desc: 'Turing Machine — unlimited read/write tape; most powerful' },
    ],
  },
  {
    id: 'chomsky',
    title: 'Chomsky Hierarchy',
    items: [
      { label: 'Type 3', desc: 'Regular — recognized by DFA/NFA; generated by regular grammars' },
      { label: 'Type 2', desc: 'Context-Free — recognized by PDA; generated by CFGs' },
      { label: 'Type 1', desc: 'Context-Sensitive — recognized by LBA' },
      { label: 'Type 0', desc: 'Recursively Enumerable — recognized by TM' },
    ],
  },
  {
    id: 'notation',
    title: 'Key Notation',
    items: [
      { label: 'Σ', desc: 'Alphabet — finite, non-empty set of symbols' },
      { label: 'Σ*', desc: 'Kleene closure — all strings over Σ including λ' },
      { label: 'λ (or ε)', desc: 'Empty string — length 0' },
      { label: '|w|', desc: 'Length of string w' },
      { label: 'w^R', desc: 'Reversal of string w' },
      { label: 'L(M)', desc: 'Language accepted by automaton M' },
      { label: '⟹*', desc: 'Derives (zero or more steps)' },
      { label: 'δ̂', desc: 'Extended transition function (reads full string)' },
    ],
  },
  {
    id: 'decidability',
    title: 'Decidability Summary',
    items: [
      { label: 'A_DFA', desc: '✓ Decidable — simulate DFA' },
      { label: 'E_DFA', desc: '✓ Decidable — DFS/BFS from start state' },
      { label: 'EQ_DFA', desc: '✓ Decidable — minimize and compare' },
      { label: 'A_CFG', desc: '✓ Decidable — CYK algorithm' },
      { label: 'A_TM', desc: '✗ Undecidable — halting problem' },
      { label: 'HALT_TM', desc: '✗ Undecidable — diagonalization' },
      { label: 'E_TM', desc: '✗ Not even recognizable' },
    ],
  },
  {
    id: 'complexity',
    title: 'Complexity Classes',
    items: [
      { label: 'P', desc: 'Polynomial time decidable (deterministic TM)' },
      { label: 'NP', desc: 'Polynomial time verifiable (or nondeterministic poly)' },
      { label: 'NP-complete', desc: 'Hardest problems in NP; SAT, 3-SAT, Clique, VertexCover...' },
      { label: 'PSPACE', desc: 'Polynomial space decidable; P ⊆ NP ⊆ PSPACE' },
      { label: 'P vs NP', desc: 'Is P=NP? Greatest open problem in CS — $1M prize!' },
    ],
  },
]

export function QuickReference() {
  return (
    <div className="space-y-4">
      <div>
        <h3 className="text-sm font-semibold text-foreground mb-1">Quick Reference</h3>
        <p className="text-xs text-muted-foreground">Key concepts at a glance</p>
      </div>
      <Accordion type="multiple" className="space-y-1">
        {refs.map((ref) => (
          <AccordionItem
            key={ref.id}
            value={ref.id}
            className="border border-border rounded-lg overflow-hidden px-0"
          >
            <AccordionTrigger className="px-3 py-2.5 text-sm font-medium hover:no-underline hover:bg-muted/50 rounded-lg">
              {ref.title}
            </AccordionTrigger>
            <AccordionContent className="px-3 pb-3">
              <ul className="space-y-2 mt-1">
                {ref.items.map((item, i) => (
                  <li key={i} className="flex gap-2 items-start">
                    <Badge variant="outline" className="text-xs shrink-0 font-mono mt-0.5 py-0">
                      {item.label}
                    </Badge>
                    <span className="text-xs text-muted-foreground leading-relaxed">{item.desc}</span>
                  </li>
                ))}
              </ul>
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  )
}
