export interface ExamQuestion {
  id: string
  chapter: string
  topic: string
  difficulty: 'easy' | 'medium' | 'hard'
  question: string
  options: string[]
  answer: number
  explanation: string
}

export const EXAM_TIME_SECONDS = 120 * 60 // 120 minutes

export const examQuestions: ExamQuestion[] = [

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 1: Formal Languages & Introduction (20 questions)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'q1_01',
    chapter: 'Chapter 1',
    topic: 'Alphabets & Strings',
    difficulty: 'easy',
    question: 'Which symbol denotes the empty string?',
    options: ['ε (epsilon/lambda)', '∅ (empty set)', 'Σ (sigma)', 'φ (phi)'],
    answer: 0,
    explanation: 'The empty string is denoted ε (epsilon) or λ (lambda). It has zero symbols and length 0. ∅ is the empty set (containing no strings).',
  },
  {
    id: 'q1_02',
    chapter: 'Chapter 1',
    topic: 'Alphabets & Strings',
    difficulty: 'easy',
    question: 'If Σ = {a, b}, what is |Σ²|?',
    options: ['2', '4', '6', '8'],
    answer: 1,
    explanation: 'Σ² is the set of all strings of length exactly 2: {aa, ab, ba, bb}. So |Σ²| = 4 = |Σ|².',
  },
  {
    id: 'q1_03',
    chapter: 'Chapter 1',
    topic: 'Alphabets & Strings',
    difficulty: 'easy',
    question: 'The length of the string w = "abba" is:',
    options: ['2', '3', '4', '5'],
    answer: 2,
    explanation: '|w| counts the number of symbols in the string. "abba" has four symbols: a, b, b, a. So |abba| = 4.',
  },
  {
    id: 'q1_04',
    chapter: 'Chapter 1',
    topic: 'Alphabets & Strings',
    difficulty: 'easy',
    question: 'What is the reversal of the string w = "abc"?',
    options: ['abc', 'cba', 'bac', 'cab'],
    answer: 1,
    explanation: 'The reversal w^R reverses the order of symbols. So "abc"^R = "cba".',
  },
  {
    id: 'q1_05',
    chapter: 'Chapter 1',
    topic: 'Language Operations',
    difficulty: 'easy',
    question: 'The Kleene star L* of a language L always includes:',
    options: [
      'Only non-empty strings from L',
      'The empty string ε and all finite concatenations of strings from L',
      'Only strings of even length',
      'The complement of L',
    ],
    answer: 1,
    explanation: 'L* = L⁰ ∪ L¹ ∪ L² ∪ … where L⁰ = {ε}. It always includes ε and all finite concatenations.',
  },
  {
    id: 'q1_06',
    chapter: 'Chapter 1',
    topic: 'Language Operations',
    difficulty: 'easy',
    question: 'Σ* denotes:',
    options: [
      'The alphabet itself',
      'The set of all finite strings over Σ including ε',
      'The set of all infinite strings over Σ',
      'All strings of length exactly n',
    ],
    answer: 1,
    explanation: 'Σ* is the Kleene closure of the alphabet Σ — the set of all finite strings (including ε) that can be formed from symbols in Σ.',
  },
  {
    id: 'q1_07',
    chapter: 'Chapter 1',
    topic: 'Regular Expressions',
    difficulty: 'easy',
    question: 'The regular expression (0+1)* describes:',
    options: [
      'All binary strings ending in 1',
      'All binary strings of even length',
      'All binary strings including the empty string',
      'Only the strings "0" and "1"',
    ],
    answer: 2,
    explanation: '(0+1)* = Σ* over {0,1}. The * allows zero or more repetitions, so it includes ε and every binary string.',
  },
  {
    id: 'q1_08',
    chapter: 'Chapter 1',
    topic: 'Language Operations',
    difficulty: 'easy',
    question: 'The concatenation of strings u = "ab" and v = "cd" is:',
    options: ['cdab', 'abcd', 'abdc', 'acbd'],
    answer: 1,
    explanation: 'Concatenation uv appends v after u, giving "abcd".',
  },
  {
    id: 'q1_09',
    chapter: 'Chapter 1',
    topic: 'Language Operations',
    difficulty: 'medium',
    question: 'If L₁ = {a, ab} and L₂ = {b, ba}, what is L₁L₂?',
    options: [
      '{ab, aba, abb, abba}',
      '{a, ab, b, ba}',
      '{ab, aba, b, ba}',
      '{ab, abb, aba, abba}',
    ],
    answer: 0,
    explanation: 'L₁L₂ = {xy | x∈L₁, y∈L₂} = {a·b, a·ba, ab·b, ab·ba} = {ab, aba, abb, abba}.',
  },
  {
    id: 'q1_10',
    chapter: 'Chapter 1',
    topic: 'Language Operations',
    difficulty: 'medium',
    question: 'If L = {a, b}, which element is in L* but NOT in L⁺?',
    options: ['a', 'ab', 'ε (empty string)', 'aa'],
    answer: 2,
    explanation: 'L* = L⁰ ∪ L⁺ includes ε (from L⁰). L⁺ = L* \\ {ε} excludes ε. So ε ∈ L* but ε ∉ L⁺.',
  },
  {
    id: 'q1_11',
    chapter: 'Chapter 1',
    topic: 'Regular Expressions',
    difficulty: 'medium',
    question: 'Which regex matches all binary strings that start with 0 and end with 1?',
    options: ['0(0+1)*1', '(0+1)*01', '01*', '0*1'],
    answer: 0,
    explanation: '0(0+1)*1 starts with 0, allows any binary symbols in the middle via (0+1)*, and ends with 1. It also matches "01" when the middle is empty.',
  },
  {
    id: 'q1_12',
    chapter: 'Chapter 1',
    topic: 'Regular Expressions',
    difficulty: 'medium',
    question: 'The regular expression a*b+ denotes:',
    options: [
      'Any number of a\'s followed by at least one b',
      'At least one a followed by any number of b\'s',
      'Exactly one a followed by exactly one b',
      'Alternating a\'s and b\'s',
    ],
    answer: 0,
    explanation: 'a* means zero or more a\'s; b+ means one or more b\'s. So a*b+ = {bⁿ | n≥1} ∪ {aᵐbⁿ | m≥1, n≥1}.',
  },
  {
    id: 'q1_13',
    chapter: 'Chapter 1',
    topic: 'Language Operations',
    difficulty: 'medium',
    question: 'Which of the following is true for any language L over Σ?',
    options: [
      'L ∩ L̄ = Σ*',
      'L ∪ L̄ = Σ*',
      'L = L̄',
      'L* = Σ* only if L = Σ',
    ],
    answer: 1,
    explanation: 'L̄ = Σ* − L, so every string is in exactly one of L or L̄. Therefore L ∪ L̄ = Σ* and L ∩ L̄ = ∅.',
  },
  {
    id: 'q1_14',
    chapter: 'Chapter 1',
    topic: 'Formal Languages',
    difficulty: 'medium',
    question: 'The Chomsky hierarchy classifies grammars into how many types?',
    options: ['2', '3', '4', '5'],
    answer: 2,
    explanation: 'The Chomsky hierarchy has four levels: Type 0 (unrestricted/recursively enumerable), Type 1 (context-sensitive), Type 2 (context-free), and Type 3 (regular).',
  },
  {
    id: 'q1_15',
    chapter: 'Chapter 1',
    topic: 'Regular Expressions',
    difficulty: 'hard',
    question: 'Which regular expression is equivalent to (ab)*a?',
    options: ['a(ba)*', 'a(ab)*', '(ab)*', 'a*(ba)*'],
    answer: 0,
    explanation: '(ab)*a generates: a, aba, ababa, … a(ba)* generates: a, a·ba, a·ba·ba, … = a, aba, ababa, … These are the same strings.',
  },
  {
    id: 'q1_16',
    chapter: 'Chapter 1',
    topic: 'Language Operations',
    difficulty: 'hard',
    question: 'The complement of Σ* is:',
    options: ['Σ', '∅ (empty language)', 'Σ+', '{ε}'],
    answer: 1,
    explanation: 'The complement of Σ* with respect to Σ* is Σ* \\ Σ* = ∅. Every string is in Σ*, so nothing is left in the complement.',
  },
  {
    id: 'q1_17',
    chapter: 'Chapter 1',
    topic: 'Formal Languages',
    difficulty: 'hard',
    question: 'If L = {aⁿ | n is prime}, which class does L belong to?',
    options: [
      'Regular language',
      'Context-free but not regular',
      'Context-sensitive but not context-free',
      'Not context-free (requires Turing machine to decide)',
    ],
    answer: 3,
    explanation: 'The set of primes grows in an irregular, non-algebraic way. {aⁿ | n is prime} cannot be accepted by a PDA and is not context-free. It requires a more powerful model.',
  },
  {
    id: 'q1_18',
    chapter: 'Chapter 1',
    topic: 'Regular Expressions',
    difficulty: 'hard',
    question: 'Which of these is NOT a valid regular expression operation?',
    options: ['Union (+)', 'Concatenation (·)', 'Kleene star (*)', 'Intersection (∩)'],
    answer: 3,
    explanation: 'The three basic regular expression operations are union, concatenation, and Kleene star. Intersection is NOT a primitive regex operation (though the resulting class is closed under it, you need separate constructions to implement it).',
  },
  {
    id: 'q1_19',
    chapter: 'Chapter 1',
    topic: 'Alphabets & Strings',
    difficulty: 'hard',
    question: 'How many distinct strings of length ≤ 2 exist over Σ = {0, 1}?',
    options: ['4', '6', '7', '8'],
    answer: 2,
    explanation: 'Length 0: {ε} = 1 string. Length 1: {0,1} = 2 strings. Length 2: {00,01,10,11} = 4 strings. Total = 1+2+4 = 7.',
  },
  {
    id: 'q1_20',
    chapter: 'Chapter 1',
    topic: 'Language Operations',
    difficulty: 'hard',
    question: 'If L₁ and L₂ are regular languages, which operation may produce a non-regular result?',
    options: ['L₁ ∪ L₂', 'L₁ · L₂ (concatenation)', 'Infinite union ⋃ᵢ Lᵢ', 'L₁*'],
    answer: 2,
    explanation: 'Regular languages are closed under finite union, concatenation, and Kleene star. However, an infinite union of regular languages can be non-regular (e.g., ⋃ₙ {aⁿbⁿ}).',
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 2: Finite Automata — DFA & NFA (20 questions)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'q2_01',
    chapter: 'Chapter 2',
    topic: 'DFA',
    difficulty: 'easy',
    question: 'A DFA is formally defined as a 5-tuple (Q, Σ, δ, q₀, F). What is δ?',
    options: ['Set of states', 'Transition function Q × Σ → Q', 'Set of accepting states', 'Start state'],
    answer: 1,
    explanation: 'δ: Q × Σ → Q is the transition function. It maps each (state, input symbol) pair to exactly one next state — this determinism defines a DFA.',
  },
  {
    id: 'q2_02',
    chapter: 'Chapter 2',
    topic: 'DFA',
    difficulty: 'easy',
    question: 'A DFA accepts a string w if and only if:',
    options: [
      'The start state is an accepting state',
      'At least one transition leads to an accepting state while reading w',
      'Processing all of w from q₀ leads to a state in F',
      'Every state visited while reading w is in F',
    ],
    answer: 2,
    explanation: 'A DFA accepts w if δ̂(q₀, w) ∈ F — the extended transition function, starting from q₀ and consuming all of w, ends in an accepting state.',
  },
  {
    id: 'q2_03',
    chapter: 'Chapter 2',
    topic: 'DFA',
    difficulty: 'easy',
    question: 'In a DFA, from any given state on any input symbol, the number of possible next states is exactly:',
    options: ['0', '1', 'At most 2', 'Any finite number'],
    answer: 1,
    explanation: 'In a DFA, δ is a total function — for every (state, symbol) pair there is exactly one next state. This is what makes it deterministic.',
  },
  {
    id: 'q2_04',
    chapter: 'Chapter 2',
    topic: 'NFA',
    difficulty: 'easy',
    question: 'An NFA differs from a DFA in that an NFA allows:',
    options: [
      'Only one accepting state',
      'Multiple possible next states and ε-transitions',
      'Transitions that move backwards on the tape',
      'A two-way read head',
    ],
    answer: 1,
    explanation: 'An NFA is non-deterministic: for a (state, symbol) pair it can have 0, 1, or many next states. It also allows ε-transitions (free moves without consuming input).',
  },
  {
    id: 'q2_05',
    chapter: 'Chapter 2',
    topic: 'NFA',
    difficulty: 'easy',
    question: 'An NFA accepts a string if:',
    options: [
      'All computation paths end in an accepting state',
      'At least one computation path ends in an accepting state',
      'The first computation path ends in an accepting state',
      'No computation path ends in a rejecting state',
    ],
    answer: 1,
    explanation: 'An NFA accepts if there EXISTS at least one accepting computation path. It rejects only if ALL paths reject (or die).',
  },
  {
    id: 'q2_06',
    chapter: 'Chapter 2',
    topic: 'DFA',
    difficulty: 'easy',
    question: 'A DFA for "binary strings with an even number of 1s" requires how many states?',
    options: ['1', '2', '3', '4'],
    answer: 1,
    explanation: 'Two states suffice: q_even (even count of 1s, start and accepting) and q_odd (odd count of 1s). Reading 1 toggles; reading 0 stays.',
  },
  {
    id: 'q2_07',
    chapter: 'Chapter 2',
    topic: 'NFA',
    difficulty: 'medium',
    question: 'The ε-closure of a state q is:',
    options: [
      'The set of states reachable from q via exactly one ε-transition',
      'The set of states reachable from q using only ε-transitions (including q itself)',
      'The set of states that have ε-transitions to q',
      'The set of all states in the NFA',
    ],
    answer: 1,
    explanation: 'ε-closure(q) = all states reachable from q by taking zero or more ε-transitions, including q itself (zero ε-moves).',
  },
  {
    id: 'q2_08',
    chapter: 'Chapter 2',
    topic: 'NFA',
    difficulty: 'medium',
    question: 'An NFA with n states, when converted to a DFA via the subset construction, has at most how many states?',
    options: ['n', '2n', '2ⁿ', 'n²'],
    answer: 2,
    explanation: 'The subset (powerset) construction builds DFA states from subsets of NFA states. With n NFA states there are 2ⁿ subsets, so the DFA has at most 2ⁿ states.',
  },
  {
    id: 'q2_09',
    chapter: 'Chapter 2',
    topic: 'DFA',
    difficulty: 'medium',
    question: 'To build a DFA accepting the complement of L (i.e., L̄), given a DFA M for L, you:',
    options: [
      'Reverse all transitions of M',
      'Swap all accepting and non-accepting states',
      'Add a new dead state',
      'Remove all transitions from accepting states',
    ],
    answer: 1,
    explanation: 'Since M is a complete DFA, swapping accepting and non-accepting states gives a DFA for L̄. Every string accepted by M is now rejected and vice versa.',
  },
  {
    id: 'q2_10',
    chapter: 'Chapter 2',
    topic: 'NFA',
    difficulty: 'medium',
    question: 'In the subset construction, the DFA start state is:',
    options: [
      'The NFA start state q₀ alone',
      'ε-closure({q₀})',
      'The set of all NFA accepting states',
      'The power set of all NFA states',
    ],
    answer: 1,
    explanation: 'The DFA start state is ε-closure({q₀}) — all states reachable from the NFA start state via ε-transitions alone.',
  },
  {
    id: 'q2_11',
    chapter: 'Chapter 2',
    topic: 'DFA',
    difficulty: 'medium',
    question: 'Which of the following languages requires at least 3 DFA states?',
    options: [
      'All strings over {a,b}',
      'Strings ending in "ab"',
      'Strings with even length',
      'Strings beginning with "a"',
    ],
    answer: 1,
    explanation: 'Recognizing "ends in ab" requires tracking the last two characters with states: default, seen-a, seen-ab. Fewer than 3 states cannot encode the two-symbol suffix memory needed.',
  },
  {
    id: 'q2_12',
    chapter: 'Chapter 2',
    topic: 'DFA',
    difficulty: 'medium',
    question: 'A dead state (trap state) in a DFA is:',
    options: [
      'The start state',
      'A non-accepting state with all transitions going to itself',
      'A state with no outgoing transitions',
      'An accepting state that is also the start state',
    ],
    answer: 1,
    explanation: 'A dead state is a non-accepting sink state: once reached, the machine stays there forever and cannot accept. It is used to make the transition function total.',
  },
  {
    id: 'q2_13',
    chapter: 'Chapter 2',
    topic: 'NFA',
    difficulty: 'hard',
    question: 'When converting an NFA to a DFA, a DFA state is an accepting state if:',
    options: [
      'It corresponds to a subset containing only NFA accepting states',
      'It corresponds to a subset containing at least one NFA accepting state',
      'It corresponds to the NFA start state',
      'It has no outgoing transitions',
    ],
    answer: 1,
    explanation: 'A DFA state (subset S of NFA states) is accepting if S ∩ F ≠ ∅ — at least one NFA state in the subset is an accepting state.',
  },
  {
    id: 'q2_14',
    chapter: 'Chapter 2',
    topic: 'DFA',
    difficulty: 'hard',
    question: 'DFA minimization using the table-filling (Myhill-Nerode) algorithm: what is the base case for marking pairs?',
    options: [
      'Pairs where both states have the same number of outgoing transitions',
      'Pairs (p,q) where exactly one of p, q is an accepting state',
      'Pairs (p,q) where both are accepting states',
      'Pairs (p,q) where p = q₀',
    ],
    answer: 1,
    explanation: 'Base case: mark (p,q) as distinguishable if exactly one of p,q is in F (accepting). These pairs can already be separated by ε.',
  },
  {
    id: 'q2_15',
    chapter: 'Chapter 2',
    topic: 'DFA',
    difficulty: 'hard',
    question: 'Two states p and q in a DFA are equivalent (indistinguishable) if:',
    options: [
      'They have the same transitions on all inputs',
      'No string distinguishes them: for all w, δ̂(p,w) ∈ F ↔ δ̂(q,w) ∈ F',
      'They are both accepting states',
      'They are both non-accepting states',
    ],
    answer: 1,
    explanation: 'States p and q are equivalent iff for every string w, processing w from p lands in an accepting state exactly when processing w from q does. No string can distinguish them.',
  },
  {
    id: 'q2_16',
    chapter: 'Chapter 2',
    topic: 'NFA',
    difficulty: 'hard',
    question: 'Which statement about NFAs and DFAs is FALSE?',
    options: [
      'Every DFA is also an NFA',
      'NFAs can recognize languages that DFAs cannot',
      'Every NFA can be converted to an equivalent DFA',
      'NFAs and DFAs recognize exactly the class of regular languages',
    ],
    answer: 1,
    explanation: 'NFAs and DFAs recognize exactly the same class — regular languages. An NFA has no more expressive power than a DFA; it just offers a more convenient description.',
  },
  {
    id: 'q2_17',
    chapter: 'Chapter 2',
    topic: 'DFA',
    difficulty: 'hard',
    question: 'The Myhill-Nerode theorem states that a language L is regular if and only if:',
    options: [
      'L has a finite number of strings',
      'The equivalence relation ≡_L has a finite index (finite number of equivalence classes)',
      'L can be described by a regular expression with no Kleene star',
      'L is accepted by an NFA with fewer than 10 states',
    ],
    answer: 1,
    explanation: 'Myhill-Nerode: L is regular iff the number of distinct right-congruence classes of ≡_L is finite. The minimum DFA has exactly as many states as the index of ≡_L.',
  },
  {
    id: 'q2_18',
    chapter: 'Chapter 2',
    topic: 'NFA',
    difficulty: 'hard',
    question: 'A GNFA (Generalized NFA) is used for:',
    options: [
      'Simulating Turing machines with fewer states',
      'Converting a DFA/NFA to an equivalent regular expression',
      'Recognizing context-free languages',
      'Minimizing DFAs more efficiently',
    ],
    answer: 1,
    explanation: 'A GNFA allows regular expressions as transition labels. The state-elimination procedure on a GNFA yields an equivalent regular expression — the standard algorithm for NFA→RegEx conversion.',
  },
  {
    id: 'q2_19',
    chapter: 'Chapter 2',
    topic: 'DFA',
    difficulty: 'hard',
    question: 'The minimum DFA for L = {w ∈ {a,b}* | w contains "aba" as a substring} has how many states?',
    options: ['3', '4', '5', '6'],
    answer: 1,
    explanation: 'You need to track the longest suffix of "aba" seen so far: 0 chars matched, matched "a", matched "ab", matched "aba" (accept/sink). That gives 4 states.',
  },
  {
    id: 'q2_20',
    chapter: 'Chapter 2',
    topic: 'DFA',
    difficulty: 'hard',
    question: 'Which closure property of regular languages follows directly from the ability to swap accepting and non-accepting states in a DFA?',
    options: ['Closure under concatenation', 'Closure under complement', 'Closure under Kleene star', 'Closure under homomorphism'],
    answer: 1,
    explanation: 'Swapping accepting and non-accepting states of a complete DFA gives the complement. This directly proves regular languages are closed under complement.',
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 3: Regular Languages, Grammars & Pumping Lemma (20 questions)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'q3_01',
    chapter: 'Chapter 3',
    topic: 'Regular Grammars',
    difficulty: 'easy',
    question: 'A right-linear grammar has productions of the form:',
    options: ['A → Ba | A → a', 'A → aB | A → a | A → ε', 'A → ABC', 'A → aBC'],
    answer: 1,
    explanation: 'Right-linear: A → aB (terminal then non-terminal), A → a (single terminal), or A → ε. The non-terminal, if present, is always on the right.',
  },
  {
    id: 'q3_02',
    chapter: 'Chapter 3',
    topic: 'Regular Grammars',
    difficulty: 'easy',
    question: 'Regular languages are equivalent to which combination?',
    options: [
      'Context-free grammars',
      'DFAs, NFAs, and regular expressions',
      'Pushdown automata',
      'Linear bounded automata',
    ],
    answer: 1,
    explanation: 'By Kleene\'s theorem, regular languages are exactly the class recognized by DFAs, NFAs, and described by regular expressions — all three formalisms are equivalent.',
  },
  {
    id: 'q3_03',
    chapter: 'Chapter 3',
    topic: 'Closure Properties',
    difficulty: 'easy',
    question: 'Which of the following is NOT a closure property of regular languages?',
    options: ['Union', 'Intersection', 'Complement', 'Infinite union'],
    answer: 3,
    explanation: 'Regular languages are closed under finite union, intersection, and complement. They are NOT closed under infinite union, which can produce non-regular languages.',
  },
  {
    id: 'q3_04',
    chapter: 'Chapter 3',
    topic: 'Regular Grammars',
    difficulty: 'easy',
    question: 'Which grammar type generates regular languages?',
    options: ['Type 0 (unrestricted)', 'Type 1 (context-sensitive)', 'Type 2 (context-free)', 'Type 3 (regular)'],
    answer: 3,
    explanation: 'In the Chomsky hierarchy, Type 3 grammars (regular grammars) generate exactly the regular languages. These correspond to right-linear or left-linear grammars.',
  },
  {
    id: 'q3_05',
    chapter: 'Chapter 3',
    topic: 'Closure Properties',
    difficulty: 'easy',
    question: 'If L₁ and L₂ are regular, is L₁ ∩ L₂ always regular?',
    options: ['Yes, by the product construction on DFAs', 'No, only if L₁ and L₂ are finite', 'No, intersection is not a closure property', 'Only if L₁ ⊆ L₂'],
    answer: 0,
    explanation: 'Regular languages are closed under intersection. The product (cross-product) construction builds a DFA for L₁ ∩ L₂ from DFAs for L₁ and L₂.',
  },
  {
    id: 'q3_06',
    chapter: 'Chapter 3',
    topic: 'Pumping Lemma',
    difficulty: 'medium',
    question: 'The Pumping Lemma for regular languages states that every string s ∈ L with |s| ≥ p can be written s = xyz where which condition holds?',
    options: [
      '|y| ≥ 1, |xy| ≤ p, and xyⁿz ∈ L for all n ≥ 0',
      '|y| ≥ 1, |yz| ≤ p, and xyⁿz ∈ L for all n ≥ 0',
      '|x| ≥ 1, |xy| ≤ p, and xyⁿz ∈ L for all n ≥ 0',
      '|y| ≥ 0, |xyz| ≤ p, and xyⁿz ∈ L for all n ≥ 1',
    ],
    answer: 0,
    explanation: 'Pumping Lemma: y is non-empty (|y|≥1), the pump is near the start (|xy|≤p), and pumping y any number of times (including 0) keeps the string in L.',
  },
  {
    id: 'q3_07',
    chapter: 'Chapter 3',
    topic: 'Pumping Lemma',
    difficulty: 'medium',
    question: 'To use the Pumping Lemma to prove a language is NOT regular, you must show:',
    options: [
      'There exists a pumping length p and a string s that cannot be pumped',
      'For ALL pumping lengths p, there EXISTS a string s ∈ L with |s| ≥ p that cannot be pumped for any valid decomposition',
      'The language is infinite',
      'The language cannot be described by a regex',
    ],
    answer: 1,
    explanation: 'You play a game: the adversary picks p; you pick s with |s|≥p; the adversary picks any valid xyz split; you show xyⁿz ∉ L for some n≥0. This holds for all valid splits.',
  },
  {
    id: 'q3_08',
    chapter: 'Chapter 3',
    topic: 'Pumping Lemma',
    difficulty: 'medium',
    question: 'To prove L = {aⁿbⁿ | n ≥ 0} is not regular, we choose s = aᵖbᵖ. Since |xy| ≤ p, what must y consist of?',
    options: [
      'A mix of a\'s and b\'s',
      'Only a\'s',
      'Only b\'s',
      'At least one a and one b',
    ],
    answer: 1,
    explanation: 'The first p characters of aᵖbᵖ are all a\'s. Since |xy| ≤ p, both x and y fall entirely within the a-region. So y = aᵏ (k≥1). Pumping changes the a-count but not b-count.',
  },
  {
    id: 'q3_09',
    chapter: 'Chapter 3',
    topic: 'Closure Properties',
    difficulty: 'medium',
    question: 'If L is regular, is L^R (reversal of all strings in L) also regular?',
    options: [
      'Yes — reverse the NFA transitions and swap start/accepting states',
      'No — reversal can create non-regular languages',
      'Only if L is finite',
      'Only if L does not contain ε',
    ],
    answer: 0,
    explanation: 'Regular languages are closed under reversal. Constructively: reverse all arrows in the DFA/NFA, swap the (set of) start state(s) and accepting states.',
  },
  {
    id: 'q3_10',
    chapter: 'Chapter 3',
    topic: 'Regular Grammars',
    difficulty: 'medium',
    question: 'A left-linear grammar has productions of the form:',
    options: ['A → aB', 'A → Ba', 'A → aBC', 'A → BC'],
    answer: 1,
    explanation: 'In a left-linear grammar every production is A → Ba (non-terminal on the left of the terminal) or A → a. Left-linear and right-linear grammars both generate exactly the regular languages.',
  },
  {
    id: 'q3_11',
    chapter: 'Chapter 3',
    topic: 'Closure Properties',
    difficulty: 'medium',
    question: 'The difference L₁ \\ L₂ = L₁ ∩ L̄₂. This means regular languages are closed under:',
    options: ['Only union', 'Set difference', 'Infinite intersection', 'Prefix closure only'],
    answer: 1,
    explanation: 'Since regular languages are closed under intersection and complement, L₁ \\ L₂ = L₁ ∩ L̄₂ is also regular. Hence they are closed under set difference.',
  },
  {
    id: 'q3_12',
    chapter: 'Chapter 3',
    topic: 'Pumping Lemma',
    difficulty: 'medium',
    question: 'Why does the Pumping Lemma NOT prove that a language IS regular?',
    options: [
      'Because only DFAs can prove regularity',
      'Because the Pumping Lemma is a necessary condition for regularity, not sufficient',
      'Because pumping only works on finite languages',
      'Because the lemma applies to all languages',
    ],
    answer: 1,
    explanation: 'The Pumping Lemma gives a necessary condition: every regular language satisfies it. But some non-regular languages also satisfy it. Passing the pumping test does not guarantee regularity.',
  },
  {
    id: 'q3_13',
    chapter: 'Chapter 3',
    topic: 'Regular Grammars',
    difficulty: 'hard',
    question: 'The right-linear grammar S → aS | bA | ε, A → aA | ε generates:',
    options: [
      '{aⁿbᵐ | n,m ≥ 0}',
      '{aⁿ(ba*)* | n ≥ 0}',
      'All strings over {a,b} not containing "bb"',
      'All strings of the form a*ba* including ε',
    ],
    answer: 1,
    explanation: 'S can produce any number of a\'s then move to A via b, and A can loop on a\'s. The result is: zero or more a\'s, optionally followed by b then any a\'s, repeated. Pattern: (a* b a*)* more precisely a*(ba*)* .',
  },
  {
    id: 'q3_14',
    chapter: 'Chapter 3',
    topic: 'Pumping Lemma',
    difficulty: 'hard',
    question: 'Which of the following languages IS regular (satisfies the pumping lemma AND has a DFA/regex)?',
    options: [
      '{aⁿbⁿ | n ≥ 1}',
      '{w | w has equal numbers of a\'s and b\'s}',
      '{aⁿ | n is a perfect square}',
      '{w ∈ {a,b}* | |w| is even}',
    ],
    answer: 3,
    explanation: 'Strings of even length form a regular language: DFA with 2 states (even/odd), accepting the even state. The others require counting that exceeds finite-state memory.',
  },
  {
    id: 'q3_15',
    chapter: 'Chapter 3',
    topic: 'Closure Properties',
    difficulty: 'hard',
    question: 'The homomorphic image of a regular language (applying a homomorphism h to each symbol) is:',
    options: [
      'Always regular',
      'Regular only if h is one-to-one',
      'Not necessarily regular',
      'Always context-free but not regular',
    ],
    answer: 0,
    explanation: 'Regular languages are closed under homomorphism. Applying h to each symbol of each string in L yields another regular language (the NFA/DFA construction adapts straightforwardly).',
  },
  {
    id: 'q3_16',
    chapter: 'Chapter 3',
    topic: 'Pumping Lemma',
    difficulty: 'hard',
    question: 'To prove L = {ww | w ∈ {a,b}*} is not regular using the Pumping Lemma, a good choice for s is:',
    options: [
      'aᵖbᵖ',
      'aᵖaᵖ',
      'aᵖbᵖaᵖbᵖ',
      '(ab)ᵖ',
    ],
    answer: 2,
    explanation: 'Choose s = aᵖbᵖaᵖbᵖ (which equals ww for w=aᵖbᵖ). Since |xy|≤p, y lies in the first a-block. Pumping changes the first half but not the second, so the two halves no longer match.',
  },
  {
    id: 'q3_17',
    chapter: 'Chapter 3',
    topic: 'Regular Grammars',
    difficulty: 'hard',
    question: 'Converting a right-linear grammar to an NFA: each non-terminal becomes a state, and a production A → aB becomes:',
    options: [
      'A ε-transition from A to B on reading a',
      'A transition from state A to state B labeled a',
      'A transition from B to A labeled a',
      'An ε-transition from A to B with no label',
    ],
    answer: 1,
    explanation: 'In the standard right-linear grammar → NFA construction, each variable is a state, A → aB becomes δ(A, a) ∋ B, and A → a (or A → aε) goes to a new accepting state on symbol a.',
  },
  {
    id: 'q3_18',
    chapter: 'Chapter 3',
    topic: 'Closure Properties',
    difficulty: 'hard',
    question: 'The quotient L/R of a regular language L with a regular language R is:',
    options: [
      '{w | ∃x ∈ R such that wx ∈ L} — always regular',
      '{w | ∀x ∈ R, wx ∈ L} — not necessarily regular',
      '{w | w is a prefix of some string in L}',
      '{w | ww ∈ L}',
    ],
    answer: 0,
    explanation: 'The right quotient L/R = {w | ∃x ∈ R, wx ∈ L} is always regular when both L and R are regular. This is a standard closure property proved by DFA construction.',
  },
  {
    id: 'q3_19',
    chapter: 'Chapter 3',
    topic: 'Pumping Lemma',
    difficulty: 'hard',
    question: 'The pumping length p in the Pumping Lemma for a regular language L corresponds to:',
    options: [
      'The length of the shortest string in L',
      'The number of states in the minimal DFA for L',
      'The number of symbols in the regex for L',
      'The index of the Myhill-Nerode equivalence classes',
    ],
    answer: 1,
    explanation: 'By the pigeonhole principle, when processing a string of length ≥ n (number of DFA states), some state repeats — that repeated portion can be pumped. So p = number of states in the minimal DFA.',
  },
  {
    id: 'q3_20',
    chapter: 'Chapter 3',
    topic: 'Regular Grammars',
    difficulty: 'hard',
    question: 'Which of the following is a necessary and sufficient condition for a language to be regular?',
    options: [
      'It satisfies the Pumping Lemma',
      'It has a finite number of strings',
      'The Myhill-Nerode equivalence ≡_L has finite index',
      'It can be recognized by a 2-stack PDA',
    ],
    answer: 2,
    explanation: 'The Myhill-Nerode theorem gives a necessary AND sufficient condition: L is regular if and only if ≡_L has finite index (finitely many equivalence classes).',
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 4: Context-Free Languages & PDAs (20 questions)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'q4_01',
    chapter: 'Chapter 4',
    topic: 'CFG',
    difficulty: 'easy',
    question: 'In a context-free grammar G = (V, T, P, S), what does T represent?',
    options: ['Non-terminals (variables)', 'Terminals (input symbols)', 'Start variable', 'Set of productions'],
    answer: 1,
    explanation: '(V,T,P,S): V = variables, T = terminals (actual alphabet symbols), P = productions, S = start variable.',
  },
  {
    id: 'q4_02',
    chapter: 'Chapter 4',
    topic: 'CFG',
    difficulty: 'easy',
    question: 'A grammar is ambiguous if:',
    options: [
      'It generates an infinite language',
      'Some string has two or more distinct parse trees (leftmost derivations)',
      'It contains ε-productions',
      'It has more variables than terminals',
    ],
    answer: 1,
    explanation: 'A grammar G is ambiguous if some w ∈ L(G) has two distinct parse trees, equivalently two distinct leftmost (or rightmost) derivations.',
  },
  {
    id: 'q4_03',
    chapter: 'Chapter 4',
    topic: 'CFG',
    difficulty: 'easy',
    question: 'What language does S → aSb | ε generate?',
    options: ['{aⁿbⁿ | n ≥ 0}', '{aⁿbᵐ | n,m ≥ 0}', '{aⁿbⁿ | n ≥ 1}', '{ww^R | w ∈ {a,b}*}'],
    answer: 0,
    explanation: 'Each application of S → aSb wraps one more a on the left and b on the right. S → ε terminates with equal counts of a\'s and b\'s: {aⁿbⁿ | n≥0}.',
  },
  {
    id: 'q4_04',
    chapter: 'Chapter 4',
    topic: 'PDA',
    difficulty: 'easy',
    question: 'A Pushdown Automaton (PDA) extends an NFA by adding:',
    options: ['A second read tape', 'A stack (pushdown store)', 'Two start states', 'Bidirectional reading'],
    answer: 1,
    explanation: 'A PDA = NFA + stack. The stack provides unbounded memory, enabling recognition of all context-free languages.',
  },
  {
    id: 'q4_05',
    chapter: 'Chapter 4',
    topic: 'CFG',
    difficulty: 'easy',
    question: 'Every regular language is also:',
    options: ['Context-sensitive but not context-free', 'Context-free', 'Recursively enumerable only', 'Not Turing-recognizable'],
    answer: 1,
    explanation: 'The Chomsky hierarchy is nested: Regular ⊂ Context-Free ⊂ Context-Sensitive ⊂ Recursively Enumerable. Every regular language is automatically context-free.',
  },
  {
    id: 'q4_06',
    chapter: 'Chapter 4',
    topic: 'CFG',
    difficulty: 'easy',
    question: 'A derivation is leftmost if at each step:',
    options: [
      'The rightmost non-terminal is replaced',
      'The leftmost non-terminal is replaced',
      'Only one non-terminal exists at each step',
      'The shortest production is always applied',
    ],
    answer: 1,
    explanation: 'In a leftmost derivation, at every step we replace the leftmost (first) non-terminal in the current sentential form.',
  },
  {
    id: 'q4_07',
    chapter: 'Chapter 4',
    topic: 'PDA',
    difficulty: 'medium',
    question: 'L = {aⁿbⁿcⁿ | n ≥ 0} is NOT context-free because:',
    options: [
      'The alphabet has three symbols',
      'A PDA stack can only match one pair of equal counts simultaneously',
      'It has no regular expression',
      'It requires an infinite grammar',
    ],
    answer: 1,
    explanation: 'A single stack can compare two counts (like aⁿbⁿ), but cannot independently verify three equal counts (a\'s = b\'s = c\'s) simultaneously.',
  },
  {
    id: 'q4_08',
    chapter: 'Chapter 4',
    topic: 'CFG',
    difficulty: 'medium',
    question: 'Chomsky Normal Form (CNF) requires all productions to be:',
    options: ['A → BC or A → a', 'A → aB or A → a', 'A → BCD or A → a', 'A → a or A → ε'],
    answer: 0,
    explanation: 'CNF: every production is A → BC (two non-terminals) or A → a (single terminal). Optionally S → ε if ε ∈ L(G). CNF simplifies algorithms like CYK parsing.',
  },
  {
    id: 'q4_09',
    chapter: 'Chapter 4',
    topic: 'PDA',
    difficulty: 'medium',
    question: 'A PDA accepts by empty stack when:',
    options: [
      'The machine enters a designated accepting state',
      'The stack is empty when all input is consumed',
      'The machine reads a blank symbol',
      'All paths lead to an empty stack',
    ],
    answer: 1,
    explanation: 'Acceptance by empty stack: the PDA accepts w if, after reading all of w, the stack is empty (regardless of the current state). This is equivalent to acceptance by final state.',
  },
  {
    id: 'q4_10',
    chapter: 'Chapter 4',
    topic: 'CFG',
    difficulty: 'medium',
    question: 'The CYK (Cocke-Younger-Kasami) algorithm works on grammars in:',
    options: ['Greibach Normal Form', 'Chomsky Normal Form', 'Any CFG', 'Only right-linear grammars'],
    answer: 1,
    explanation: 'CYK requires the grammar to be in CNF. It fills a table in O(n³) time to determine if a string of length n belongs to the language.',
  },
  {
    id: 'q4_11',
    chapter: 'Chapter 4',
    topic: 'CFG',
    difficulty: 'medium',
    question: 'The CFL Pumping Lemma requires any long enough string s = uvxyz where:',
    options: [
      '|vy| ≥ 1, |vxy| ≤ p, and uvⁿxyⁿz ∈ L for all n ≥ 0',
      '|ux| ≥ 1, |vxy| ≤ p, and uvⁿxyⁿz ∈ L',
      '|vy| ≥ 1, |uvx| ≤ p',
      '|v| ≥ 1, |y| ≥ 1',
    ],
    answer: 0,
    explanation: 'CFL Pumping Lemma: at least one of v,y is non-empty (|vy|≥1), the middle is bounded (|vxy|≤p), and pumping v and y together (same number of times) preserves L-membership.',
  },
  {
    id: 'q4_12',
    chapter: 'Chapter 4',
    topic: 'PDA',
    difficulty: 'medium',
    question: 'Which of the following languages is context-free but NOT regular?',
    options: [
      '{w ∈ {a,b}* | |w| is even}',
      '{aⁿbⁿ | n ≥ 0}',
      '{aⁿ | n ≥ 0}',
      '{w | w starts with a}',
    ],
    answer: 1,
    explanation: '{aⁿbⁿ} is the canonical example: generated by S → aSb | ε (CFL), but not regular (fails the Pumping Lemma for regular languages).',
  },
  {
    id: 'q4_13',
    chapter: 'Chapter 4',
    topic: 'CFG',
    difficulty: 'hard',
    question: 'Greibach Normal Form (GNF) requires every production to be:',
    options: ['A → BC', 'A → aα where a is a terminal and α ∈ V*', 'A → a or A → AB', 'A → αa where a is a terminal'],
    answer: 1,
    explanation: 'GNF: every production A → aα where a is a single terminal and α is a (possibly empty) string of non-terminals. GNF ensures every derivation step consumes exactly one input symbol.',
  },
  {
    id: 'q4_14',
    chapter: 'Chapter 4',
    topic: 'CFG',
    difficulty: 'hard',
    question: 'Which statement about inherently ambiguous languages is true?',
    options: [
      'Every CFL has an unambiguous grammar',
      'Some CFLs are inherently ambiguous — every grammar for them is ambiguous',
      'Inherently ambiguous languages are not context-free',
      'Ambiguity is always resolvable by converting to CNF',
    ],
    answer: 1,
    explanation: 'Some CFLs are inherently ambiguous: no matter what CFG you write for them, the grammar is ambiguous. The classic example is {aⁱbⁱcʲdʲ | i,j≥0} ∪ {aⁱbʲcʲdⁱ | i,j≥0}.',
  },
  {
    id: 'q4_15',
    chapter: 'Chapter 4',
    topic: 'PDA',
    difficulty: 'hard',
    question: 'The class of context-free languages is NOT closed under:',
    options: ['Union', 'Concatenation', 'Intersection', 'Kleene star'],
    answer: 2,
    explanation: 'CFLs are closed under union, concatenation, and Kleene star, but NOT under intersection. Counterexample: {aⁿbⁿcᵐ} ∩ {aᵐbⁿcⁿ} = {aⁿbⁿcⁿ}, which is not context-free.',
  },
  {
    id: 'q4_16',
    chapter: 'Chapter 4',
    topic: 'PDA',
    difficulty: 'hard',
    question: 'A deterministic PDA (DPDA) is strictly LESS powerful than a non-deterministic PDA because:',
    options: [
      'DPDAs can only have one stack symbol',
      'Some context-free languages (like {ww^R}) cannot be accepted by any DPDA',
      'DPDAs cannot accept by empty stack',
      'DPDAs have no ε-transitions',
    ],
    answer: 1,
    explanation: 'DPDAs recognize a proper subset of CFLs called deterministic CFLs. {ww^R} (palindromes) is a CFL that requires non-determinism to recognize — no DPDA can accept it.',
  },
  {
    id: 'q4_17',
    chapter: 'Chapter 4',
    topic: 'CFG',
    difficulty: 'hard',
    question: 'To convert a CFG to CNF, which step removes unit productions (A → B)?',
    options: [
      'Replace A → B with all productions reachable from B',
      'Add ε-productions from A for each production of B',
      'Merge variables A and B into a single state',
      'Remove B from the grammar entirely',
    ],
    answer: 0,
    explanation: 'To eliminate unit production A → B: for each B → α (where α is not a single variable), add A → α to the grammar. Repeat transitively.',
  },
  {
    id: 'q4_18',
    chapter: 'Chapter 4',
    topic: 'CFG',
    difficulty: 'hard',
    question: 'The Earley parsing algorithm recognises a string of length n in a CFL in time:',
    options: ['O(n)', 'O(n²)', 'O(n³)', 'O(2ⁿ)'],
    answer: 2,
    explanation: 'Earley\'s algorithm parses any CFL in O(n³) time and O(n²) space in the worst case, and O(n) for unambiguous grammars.',
  },
  {
    id: 'q4_19',
    chapter: 'Chapter 4',
    topic: 'PDA',
    difficulty: 'hard',
    question: 'Every context-free language is accepted by a PDA with how many states in the simplest construction?',
    options: ['One state', 'Two states', 'Three states', 'One state per grammar variable'],
    answer: 2,
    explanation: 'The standard CFG→PDA construction uses three states: a start state, a loop state (where all grammar simulation happens), and a accept state. The grammar is simulated on the stack.',
  },
  {
    id: 'q4_20',
    chapter: 'Chapter 4',
    topic: 'CFG',
    difficulty: 'hard',
    question: 'Which statement is TRUE about CFLs and intersection?',
    options: [
      'CFL ∩ CFL is always a CFL',
      'CFL ∩ Regular is always a CFL',
      'CFL ∩ CFL is always regular',
      'CFL ∩ Regular is not always a CFL',
    ],
    answer: 1,
    explanation: 'The intersection of a CFL with a regular language is always a CFL (proved by simultaneously running the PDA and DFA). But two CFLs intersected can be non-context-free.',
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 5: Turing Machines & Computability (20 questions)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'q5_01',
    chapter: 'Chapter 5',
    topic: 'Turing Machines',
    difficulty: 'easy',
    question: 'A Turing Machine\'s tape is:',
    options: ['Finite and fixed-size', 'Finite but expandable', 'Infinite in both directions', 'Bounded by the input length'],
    answer: 2,
    explanation: 'A TM\'s tape is infinite in both directions. Cells not yet written contain the blank symbol ⊔.',
  },
  {
    id: 'q5_02',
    chapter: 'Chapter 5',
    topic: 'Turing Machines',
    difficulty: 'easy',
    question: 'A TM transition δ(q, a) = (p, b, R) means:',
    options: [
      'In state q reading a: write b, move Right, go to state p',
      'In state p reading b: write a, move Right, go to state q',
      'Accept if in state q, reading a, else write b and go Right',
      'In state q: move Right, go to p, then write b',
    ],
    answer: 0,
    explanation: 'δ(q,a) = (p,b,R): in state q, reading a — write b on current cell, move head Right, transition to state p.',
  },
  {
    id: 'q5_03',
    chapter: 'Chapter 5',
    topic: 'Turing Machines',
    difficulty: 'easy',
    question: 'A configuration of a Turing Machine consists of:',
    options: [
      'Only the current state',
      'The current state, the tape contents, and the head position',
      'The input string and the set of accepting states',
      'The transition function and the current state',
    ],
    answer: 1,
    explanation: 'A TM configuration captures everything needed to continue computation: current state, full tape contents, and current head position.',
  },
  {
    id: 'q5_04',
    chapter: 'Chapter 5',
    topic: 'Decidability',
    difficulty: 'easy',
    question: 'A language L is Turing-decidable (recursive) if:',
    options: [
      'There exists a TM that accepts all strings in L',
      'There exists a TM that always halts and accepts strings in L and rejects strings not in L',
      'There exists a TM that loops on strings not in L',
      'There is no TM that rejects any string in L',
    ],
    answer: 1,
    explanation: 'A decidable language has a TM decider: it halts on every input, accepting inputs in L and rejecting inputs not in L.',
  },
  {
    id: 'q5_05',
    chapter: 'Chapter 5',
    topic: 'Turing Machines',
    difficulty: 'easy',
    question: 'The Church-Turing Thesis states:',
    options: [
      'Every algorithm runs in polynomial time on a TM',
      'Every effectively computable function can be computed by a Turing Machine',
      'All languages are Turing-recognizable',
      'NTMs are more powerful than deterministic TMs',
    ],
    answer: 1,
    explanation: 'The Church-Turing Thesis: the informal notion of "effective computation" is captured exactly by Turing machines. It is a thesis, not a theorem — it cannot be formally proved.',
  },
  {
    id: 'q5_06',
    chapter: 'Chapter 5',
    topic: 'Decidability',
    difficulty: 'easy',
    question: 'A Turing-recognizable (recursively enumerable) language is one where:',
    options: [
      'A TM always halts and accepts or rejects',
      'A TM accepts strings in L but may loop forever on strings not in L',
      'No TM can accept the language',
      'A TM rejects all strings not in L in constant time',
    ],
    answer: 1,
    explanation: 'Turing-recognizable (RE): there exists a TM that accepts every string in L. For strings not in L, the TM may reject OR loop forever (never halt).',
  },
  {
    id: 'q5_07',
    chapter: 'Chapter 5',
    topic: 'Decidability',
    difficulty: 'medium',
    question: 'The Halting Problem is:',
    options: [
      'Turing-decidable',
      'Turing-recognizable but not decidable',
      'Not even Turing-recognizable',
      'Decidable only for deterministic TMs',
    ],
    answer: 1,
    explanation: 'HALT_TM is Turing-recognizable (simulate M on w, accept if M halts and accepts). But it is undecidable — Turing proved no TM can always determine whether an arbitrary TM halts.',
  },
  {
    id: 'q5_08',
    chapter: 'Chapter 5',
    topic: 'Decidability',
    difficulty: 'medium',
    question: 'The undecidability of the Halting Problem is proven using:',
    options: [
      'The pumping lemma',
      'Diagonalization / self-reference argument',
      'Reduction from the Post Correspondence Problem',
      'The CYK algorithm',
    ],
    answer: 1,
    explanation: 'Turing\'s proof: assume decider H exists for HALT; construct D that on input <M>: if H says M(⟨M⟩) halts, then D loops; otherwise D halts. Running D on ⟨D⟩ yields a contradiction.',
  },
  {
    id: 'q5_09',
    chapter: 'Chapter 5',
    topic: 'Decidability',
    difficulty: 'medium',
    question: 'If A ≤ₘ B (A is many-one reducible to B) and B is decidable, then:',
    options: ['A is decidable', 'A is undecidable', 'B is undecidable', 'A is Turing-recognizable only'],
    answer: 0,
    explanation: 'If A ≤ₘ B and B is decidable, we can decide A by: map the input via the reduction function, then use B\'s decider. So A is also decidable.',
  },
  {
    id: 'q5_10',
    chapter: 'Chapter 5',
    topic: 'Decidability',
    difficulty: 'medium',
    question: 'If A ≤ₘ B and A is undecidable, then:',
    options: ['B is decidable', 'B is undecidable', 'B is Turing-recognizable', 'No conclusion about B'],
    answer: 1,
    explanation: 'Contrapositive: if A ≤ₘ B and A is undecidable, then B must also be undecidable. (If B were decidable, A would be decidable — contradiction.)',
  },
  {
    id: 'q5_11',
    chapter: 'Chapter 5',
    topic: 'Turing Machines',
    difficulty: 'medium',
    question: 'A multitape Turing Machine is:',
    options: [
      'More powerful than a single-tape TM (recognizes more languages)',
      'Equivalent in power to a single-tape TM (same languages, potentially faster)',
      'Less powerful than a single-tape TM',
      'Equivalent only for decidable languages',
    ],
    answer: 1,
    explanation: 'Multitape TMs can be simulated by single-tape TMs (with polynomial overhead). They recognize exactly the same class of languages — they are more convenient but not more powerful.',
  },
  {
    id: 'q5_12',
    chapter: 'Chapter 5',
    topic: 'Decidability',
    difficulty: 'medium',
    question: 'The language A_TM = {⟨M,w⟩ | M is a TM and M accepts w} is:',
    options: [
      'Decidable',
      'Turing-recognizable but not decidable',
      'Co-Turing-recognizable only',
      'Not Turing-recognizable',
    ],
    answer: 1,
    explanation: 'A_TM is Turing-recognizable (universal TM simulates M on w, accepts when M accepts). It is undecidable — proved equivalent to HALT_TM, which is undecidable.',
  },
  {
    id: 'q5_13',
    chapter: 'Chapter 5',
    topic: 'Turing Machines',
    difficulty: 'hard',
    question: 'A non-deterministic TM (NTM) is equivalent in computational power to a deterministic TM because:',
    options: [
      'NTMs can only make finitely many choices',
      'Every NTM computation tree can be simulated by a deterministic BFS over all branches',
      'NTMs always halt',
      'NTMs cannot write to the tape',
    ],
    answer: 1,
    explanation: 'A deterministic TM can simulate an NTM by doing a BFS (breadth-first search) over all possible computation branches. This shows NTMs and DTMs recognize the same class of languages.',
  },
  {
    id: 'q5_14',
    chapter: 'Chapter 5',
    topic: 'Decidability',
    difficulty: 'hard',
    question: 'Rice\'s Theorem states that any non-trivial semantic property of Turing machines is:',
    options: [
      'Always decidable',
      'Undecidable',
      'Turing-recognizable but not decidable',
      'Decidable only for finite languages',
    ],
    answer: 1,
    explanation: 'Rice\'s Theorem: every non-trivial property of the language recognized by a TM is undecidable. "Non-trivial" means: neither all TMs nor no TMs have the property.',
  },
  {
    id: 'q5_15',
    chapter: 'Chapter 5',
    topic: 'Decidability',
    difficulty: 'hard',
    question: 'The complement of A_TM is:',
    options: [
      'Decidable',
      'Turing-recognizable',
      'Not Turing-recognizable',
      'Turing-recognizable but not decidable',
    ],
    answer: 2,
    explanation: 'A_TM is Turing-recognizable but not decidable. If its complement were also Turing-recognizable, A_TM would be decidable — contradiction. So the complement of A_TM is NOT Turing-recognizable.',
  },
  {
    id: 'q5_16',
    chapter: 'Chapter 5',
    topic: 'Turing Machines',
    difficulty: 'hard',
    question: 'The Universal Turing Machine (UTM) takes as input:',
    options: [
      'Only the encoding ⟨M⟩ of a TM',
      'An encoding ⟨M,w⟩ of a TM M and input string w, then simulates M on w',
      'A program and outputs its output',
      'Two TMs and checks if they are equivalent',
    ],
    answer: 1,
    explanation: 'The UTM takes ⟨M,w⟩ and simulates TM M running on input w. It accepts iff M accepts w. This is the theoretical foundation of modern programmable computers.',
  },
  {
    id: 'q5_17',
    chapter: 'Chapter 5',
    topic: 'Decidability',
    difficulty: 'hard',
    question: 'The Post Correspondence Problem (PCP) is:',
    options: [
      'Decidable for all instances',
      'Undecidable in general',
      'Decidable only when the alphabet has one symbol',
      'Equivalent to regular language membership',
    ],
    answer: 1,
    explanation: 'The PCP (given a set of domino pairs, can you form a sequence where the top and bottom strings match?) is undecidable. It is often used as a basis for other undecidability proofs.',
  },
  {
    id: 'q5_18',
    chapter: 'Chapter 5',
    topic: 'Decidability',
    difficulty: 'hard',
    question: 'A language is co-Turing-recognizable if:',
    options: [
      'It is decidable',
      'Its complement is Turing-recognizable',
      'It is Turing-recognizable and decidable',
      'It cannot be recognized by any TM',
    ],
    answer: 1,
    explanation: 'A language L is co-RE if its complement L̄ is Turing-recognizable (RE). L is decidable iff both L and L̄ are Turing-recognizable.',
  },
  {
    id: 'q5_19',
    chapter: 'Chapter 5',
    topic: 'Turing Machines',
    difficulty: 'hard',
    question: 'The number of distinct Turing machines (up to equivalence) is:',
    options: ['Finite', 'Countably infinite', 'Uncountably infinite', 'Depends on the alphabet size'],
    answer: 1,
    explanation: 'TMs can be encoded as finite strings over a fixed alphabet, so the set of all TMs is countable (countably infinite). However, the set of all languages over Σ is uncountable — so most languages have no TM.',
  },
  {
    id: 'q5_20',
    chapter: 'Chapter 5',
    topic: 'Decidability',
    difficulty: 'hard',
    question: 'Which of the following problems about TMs IS decidable?',
    options: [
      'Does TM M accept string w?',
      'Does TM M halt on all inputs?',
      'Does TM M accept at least one string?',
      'Does TM M accept the empty string ε, given that M has at most 5 states?',
    ],
    answer: 3,
    explanation: 'With a bounded finite-state TM (fixed max number of states), we can enumerate all computation paths in bounded time — it\'s decidable. The others (A_TM, E_TM, HALT_TM) are all undecidable.',
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 6: Complexity Theory — P, NP, Decidability (20 questions)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'q6_01',
    chapter: 'Chapter 6',
    topic: 'Complexity Classes',
    difficulty: 'easy',
    question: 'The class P contains all problems:',
    options: [
      'Solvable in polynomial space',
      'Solvable by a deterministic TM in polynomial time',
      'Solvable by a non-deterministic TM in polynomial time',
      'Not solvable by any TM',
    ],
    answer: 1,
    explanation: 'P = the class of decision problems solvable by a deterministic TM in O(nᵏ) time for some constant k.',
  },
  {
    id: 'q6_02',
    chapter: 'Chapter 6',
    topic: 'Complexity Classes',
    difficulty: 'easy',
    question: 'The class NP contains all problems:',
    options: [
      'Not solvable in polynomial time',
      'Solvable by a non-deterministic TM in polynomial time',
      'Solvable in linear time',
      'Requiring exponential space',
    ],
    answer: 1,
    explanation: 'NP = the class of decision problems solvable by a non-deterministic TM in polynomial time, equivalently: problems whose solutions can be verified in polynomial time.',
  },
  {
    id: 'q6_03',
    chapter: 'Chapter 6',
    topic: 'Complexity Classes',
    difficulty: 'easy',
    question: 'Which of the following is an equivalent characterization of NP?',
    options: [
      'Problems with no known polynomial-time algorithm',
      'Problems where a proposed solution ("certificate") can be verified in polynomial time',
      'Problems solvable in O(n log n) time',
      'Problems in exponential time but not polynomial time',
    ],
    answer: 1,
    explanation: 'NP can be defined by verifiers: a language is in NP iff there exists a polynomial-time verifier V such that w ∈ L ↔ ∃ certificate c with |c| = poly(|w|) and V(w,c) accepts.',
  },
  {
    id: 'q6_04',
    chapter: 'Chapter 6',
    topic: 'Complexity Classes',
    difficulty: 'easy',
    question: 'Which relationship is known to be true about P and NP?',
    options: ['P = NP', 'P ≠ NP', 'P ⊆ NP', 'NP ⊆ P'],
    answer: 2,
    explanation: 'It is known that P ⊆ NP (every deterministic poly-time algorithm is also a non-deterministic one). Whether P = NP remains the greatest open problem in computer science.',
  },
  {
    id: 'q6_05',
    chapter: 'Chapter 6',
    topic: 'NP-Completeness',
    difficulty: 'easy',
    question: 'SAT (Boolean satisfiability) was proven NP-complete by:',
    options: ['Turing', 'Cook-Levin theorem (1971)', 'Church', 'Karp'],
    answer: 1,
    explanation: 'The Cook-Levin theorem (1971) showed SAT is NP-complete — the first NP-completeness proof. Every problem in NP can be reduced to SAT in polynomial time.',
  },
  {
    id: 'q6_06',
    chapter: 'Chapter 6',
    topic: 'Complexity Classes',
    difficulty: 'easy',
    question: 'PSPACE contains all problems:',
    options: [
      'Solvable in polynomial time',
      'Solvable using polynomial space (memory)',
      'Not solvable in polynomial time',
      'Solvable only by non-deterministic machines',
    ],
    answer: 1,
    explanation: 'PSPACE = problems decidable by a TM using at most polynomial space O(nᵏ). Known: P ⊆ NP ⊆ PSPACE.',
  },
  {
    id: 'q6_07',
    chapter: 'Chapter 6',
    topic: 'NP-Completeness',
    difficulty: 'medium',
    question: 'A problem X is NP-complete if:',
    options: [
      'X ∈ NP only',
      'X ∈ NP and every problem in NP is poly-time reducible to X',
      'X is solvable in polynomial time',
      'X is not in NP but is NP-hard',
    ],
    answer: 1,
    explanation: 'X is NP-complete iff (1) X ∈ NP and (2) every Y ∈ NP satisfies Y ≤ₚ X (poly-time many-one reduction). Both conditions are required.',
  },
  {
    id: 'q6_08',
    chapter: 'Chapter 6',
    topic: 'NP-Completeness',
    difficulty: 'medium',
    question: 'If A ≤ₚ B (A poly-time reduces to B) and A is NP-complete, what can you conclude about B?',
    options: [
      'B is in P',
      'B is NP-hard',
      'B is NP-complete',
      'B is undecidable',
    ],
    answer: 1,
    explanation: 'If an NP-complete problem A reduces to B, then B is NP-hard (at least as hard as everything in NP). If also B ∈ NP, then B is NP-complete.',
  },
  {
    id: 'q6_09',
    chapter: 'Chapter 6',
    topic: 'NP-Completeness',
    difficulty: 'medium',
    question: 'Which of the following is a classic NP-complete problem?',
    options: [
      'Sorting a list of n numbers',
      'Finding the shortest path in a graph (single source)',
      '3-SAT (3-CNF satisfiability)',
      'Determining if a graph is connected',
    ],
    answer: 2,
    explanation: '3-SAT (is there a satisfying assignment for a formula in 3-CNF?) is NP-complete. Sorting, shortest path, and connectivity are all in P.',
  },
  {
    id: 'q6_10',
    chapter: 'Chapter 6',
    topic: 'Complexity Classes',
    difficulty: 'medium',
    question: 'Space complexity PSPACE vs time complexity NP: which containment is known?',
    options: ['NP ⊆ PSPACE', 'PSPACE ⊆ NP', 'NP = PSPACE', 'PSPACE and NP are incomparable'],
    answer: 0,
    explanation: 'It is known that NP ⊆ PSPACE (you can simulate NTM poly-time by using poly-space). Whether NP = PSPACE is unknown.',
  },
  {
    id: 'q6_11',
    chapter: 'Chapter 6',
    topic: 'NP-Completeness',
    difficulty: 'medium',
    question: 'If P = NP were proven, which consequence would follow?',
    options: [
      'All NP-complete problems would have polynomial-time algorithms',
      'Cryptographic systems based on factoring would still be secure',
      'NP-complete problems would become undecidable',
      'The halting problem would become decidable',
    ],
    answer: 0,
    explanation: 'If P = NP, then every NP problem (including NP-complete problems like factoring-based crypto, scheduling, etc.) could be solved in polynomial time, breaking most modern cryptography.',
  },
  {
    id: 'q6_12',
    chapter: 'Chapter 6',
    topic: 'Complexity Classes',
    difficulty: 'medium',
    question: 'The travelling salesman problem (decision version: "Is there a tour of cost ≤ k?") is:',
    options: ['In P', 'NP-complete', 'Decidable but not in NP', 'Undecidable'],
    answer: 1,
    explanation: 'TSP decision is NP-complete. A certificate (a specific tour) can be verified in polynomial time, and SAT reduces to it polynomially.',
  },
  {
    id: 'q6_13',
    chapter: 'Chapter 6',
    topic: 'Complexity Classes',
    difficulty: 'hard',
    question: 'The class coNP contains:',
    options: [
      'All problems NOT in NP',
      'Problems whose complement is in NP',
      'Problems solvable in co-polynomial time',
      'Problems both in P and NP',
    ],
    answer: 1,
    explanation: 'coNP = {L | L̄ ∈ NP}. It contains problems whose "no" instances have polynomial certificates (e.g., TAUTOLOGY). Whether NP = coNP is open.',
  },
  {
    id: 'q6_14',
    chapter: 'Chapter 6',
    topic: 'NP-Completeness',
    difficulty: 'hard',
    question: 'The Vertex Cover problem is NP-complete. If CLIQUE ≤ₚ Vertex Cover, and Vertex Cover ∈ NP, then:',
    options: [
      'CLIQUE is in P',
      'Vertex Cover is NP-complete',
      'CLIQUE must be in P',
      'Vertex Cover is undecidable',
    ],
    answer: 1,
    explanation: 'CLIQUE is NP-complete. CLIQUE ≤ₚ Vertex Cover means Vertex Cover is NP-hard. Since Vertex Cover ∈ NP, it is NP-complete.',
  },
  {
    id: 'q6_15',
    chapter: 'Chapter 6',
    topic: 'Complexity Classes',
    difficulty: 'hard',
    question: 'EXP (EXPTIME) contains:',
    options: [
      'Problems solvable in polynomial space',
      'Problems solvable in exponential time 2^(nᵏ)',
      'Problems requiring exponential space',
      'Only undecidable problems',
    ],
    answer: 1,
    explanation: 'EXPTIME = problems solvable in time O(2^(nᵏ)) for some k. Known: P ⊊ EXPTIME (by the time hierarchy theorem). NP ⊆ EXPTIME.',
  },
  {
    id: 'q6_16',
    chapter: 'Chapter 6',
    topic: 'NP-Completeness',
    difficulty: 'hard',
    question: 'Karp\'s 21 NP-complete problems (1972) were shown NP-complete by:',
    options: [
      'Direct diagonalization',
      'Polynomial-time reductions from SAT or 3-SAT',
      'Converting each problem to a Turing machine',
      'Showing each problem is in PSPACE',
    ],
    answer: 1,
    explanation: 'Karp established the NP-completeness of 21 combinatorial problems by chaining polynomial-time reductions starting from SAT/3-SAT (Cook-Levin). This bootstrapped the field of NP-completeness.',
  },
  {
    id: 'q6_17',
    chapter: 'Chapter 6',
    topic: 'Complexity Classes',
    difficulty: 'hard',
    question: 'The time hierarchy theorem states:',
    options: [
      'P = NP for all reasonable time bounds',
      'There exist problems solvable in O(t(n)) time but NOT in o(t(n)/log t(n)) time',
      'All problems in PSPACE are also in NP',
      'NTMs are exponentially faster than DTMs',
    ],
    answer: 1,
    explanation: 'The time hierarchy theorem: for any "nice" time function t, DTIME(t(n)) ⊊ DTIME(t(n)·log t(n)). More time strictly means more power — the hierarchy is strict.',
  },
  {
    id: 'q6_18',
    chapter: 'Chapter 6',
    topic: 'NP-Completeness',
    difficulty: 'hard',
    question: 'The 3-coloring problem (can you color a graph with 3 colors so no adjacent vertices share a color?) is:',
    options: ['In P', 'NP-complete', 'Undecidable', 'In PSPACE but not NP'],
    answer: 1,
    explanation: '3-coloring is NP-complete. Verification is poly-time (check each edge), and 3-SAT reduces to 3-coloring polynomially.',
  },
  {
    id: 'q6_19',
    chapter: 'Chapter 6',
    topic: 'Complexity Classes',
    difficulty: 'hard',
    question: 'Savitch\'s Theorem states that NSPACE(f(n)) ⊆ DSPACE(f(n)²). What does this imply?',
    options: [
      'Non-determinism gives no benefit in space complexity',
      'NPSPACE = PSPACE (non-deterministic polynomial space equals deterministic polynomial space)',
      'P = NP',
      'Every NP problem is solvable in linear space',
    ],
    answer: 1,
    explanation: 'By Savitch\'s Theorem: NPSPACE ⊆ DSPACE((poly)²) = DSPACE(poly) = PSPACE. So NPSPACE = PSPACE — non-determinism does not help for polynomial space.',
  },
  {
    id: 'q6_20',
    chapter: 'Chapter 6',
    topic: 'NP-Completeness',
    difficulty: 'hard',
    question: 'If someone proves P ≠ NP, which of the following is the correct implication?',
    options: [
      'No NP problem can be solved in polynomial time',
      'NP-complete problems have no polynomial-time algorithm, and NP-hard problems outside NP are still hard',
      'All NP-complete problems become undecidable',
      'P becomes empty',
    ],
    answer: 1,
    explanation: 'P ≠ NP implies NP-complete problems have no poly-time algorithm (they are truly harder than P). It does not affect decidability — NP-complete problems remain decidable, just hard.',
  },
]
